//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebloaterTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DebloaterTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;title&gt;EULA&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;style&gt;
        ///        * {
        ///            margin: 0;
        ///            padding: 0;
        ///            box-sizing: border-box;
        ///        }
        ///
        ///        html, body {
        ///            height: 100%;
        ///        }
        ///
        ///        body {
        ///            background-color: #1e1e1e;
        ///            font-family: Arial, sans-serif;
        ///            color: #ffffff;
        ///            display: table;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EULA {
            get {
                return ResourceManager.GetString("EULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;DebloaterTool&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            margin: 0;
        ///            font-family: Arial, sans-serif;
        ///            background: #121212;
        ///            color: #e0e0e0;
        ///            padding: 40px;
        ///            text-align: center;
        ///            padding-top: 250px;
        ///            transition: padding-top 0.4s cubic-bezier(0.4, 0, 0.2, 1);
        ///            scrollbar-face-color: #333333;
        ///            scrollbar-track-color: # [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set fso = CreateObject(&quot;Scripting.FileSystemObject&quot;)
        ///Set shell = CreateObject(&quot;WScript.Shell&quot;)
        ///
        ///&apos; Current script path
        ///currentPath = WScript.ScriptFullName
        ///
        ///&apos; Startup folder path
        ///startupPath = shell.SpecialFolders(&quot;Startup&quot;) &amp; &quot;\ThankYou.vbs&quot;
        ///
        ///&apos; Check if already in Startup folder
        ///If LCase(currentPath) &lt;&gt; LCase(startupPath) Then
        ///    &apos; Not in startup: copy itself there
        ///    On Error Resume Next
        ///    fso.CopyFile currentPath, startupPath, True
        ///    On Error GoTo 0
        ///Else
        ///    &apos; Create DebloaterTool Pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
